version: "3.1"

services:
    jenkin-docker:
        image: docker:dind
        container_name: jenkin-docker
        user: root
        volumes: 
            # - ./jenkins/data:/var/jenkins_home
            - jenkins-docker-certs:/certs/client
            - jenkins-data:/var/jenkins_home
            # - ./jenkins/certs:/certs/client
        environment:
            # - DOCKER_CERT_PATH=/certs/client
            - DOCKER_TLS_CERTDIR=/certs
        networks:
            jenkins_net:
                aliases:
                    - docker
        ports: 
            - "2375:2375"
        restart: always
    jenkin:
        
        build:
            context: ./stacks/jenkins
        image: jenkins-blueocean
        container_name: jenkins-blueocean
        volumes: 
            - jenkins-docker-certs:/certs/client:ro
            - jenkins-data:/var/jenkins_home
            # - /var/run/docker.sock:/var/run/docker.sock
            # - /usr/local/bin/docker:/usr/local/bin/docker
            # - /usr/bin/docker:/usr/bin/docker
            # - ./jenkins/data:/var/jenkins_home
            # - ./jenkins/certs:/certs/client
        environment:
            - DOCKER_HOST=tcp://host.docker.internal:2375
            - DOCKER_CERT_PATH=/certs/client
            # - DOCKER_TLS_VERIFY=1
        networks:
            - jenkins_net
        restart: always
        links:
            - "jenkin-docker"
        ports: 
            - "8080:8080"
            - "50000:50000"
    
    mongodb:
        build:
            context: ./stacks/mongodb
        image: mongo
        container_name: mongodb
        ports:
            - 27017:27017
        environment:
            - MONGO_INITDB_DATABASE=test
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=admin
        volumes:
            # seeding scripts
            # - ./mongo-entrypoint:/docker-entrypoint-initdb.d
            # named volumes
            - mongodb:/data/db
            - mongoconfig:/data/configdb
        networks:
            - mongo_net
        restart: always
#   client:
#     build:
#       context: ./client
#     container_name: node-client
#     image: node-client
#     volumes: 
#       - ./client/src:/app/src
#     env_file: ./client/.env
#     environment:
#       LOGLEVEL: "info"
#     command: /bin/sh -c "npm start"
#     # restart: always

#   math:
#     build:
#       context: ./math
#     image: node-math
#     container_name: node-math
#     volumes: 
#       - ./math/src:/app/src
#     env_file: ./math/.env
#     environment:
#       LOGLEVEL: "info"
#     command: /bin/sh -c "npm start"
#     # restart: always
volumes:
    jenkins-data:
    jenkins-docker-certs:
    mongodb:
    mongoconfig:
networks:
    jenkins_net:
    mongo_net: 
        driver: bridge

